### PR TITLE
Added Notice and LogoUrl to Markets

### PR DESCRIPTION
**Pull request by cohowap**
Updated the Markets object to include the "Notice" which notifies if the market is in maintenance or if it's going away.  While I was in there, I also added the LogoUrl for completeness.

### CODE REVIEW

**Comment by JKorf** [comment]
Hi, if I go to https://bittrex.com/api/v1.1/public/getcurrencies I don't see the LogoUrl you mention. Where did you see this property?

**Comment by cooljbg** [comment]
LogoUrl is here https://bittrex.com/api/v1.1/public/getmarkets

**Comment by JKorf** [comment]
Ah, my bad, looking at the wrong Url. Fair enough. You happen to know what the IsSponsored field is?

**Comment by cohowap** [comment]
IsSponsored is a marketing field.  You can pay bittrex something like 5BTC to have your coin show up with sponsored text and have it look like it had high volume or biggest gains.

**Comment by cohowap** [comment]
I didnt notice the IsSponsored, I can add that to this PR later tonight if it's something that you feel should be included.

**Comment by JKorf** [comment]
Would be good to add IsSponsored, just for completeness. I'm not sure what possible values are though

**Comment by cohowap** [comment]
I'll do the research.  Probably just a Boolean.  I'll update the PR when it's done.

**Comment by JKorf** [comment]
Any luck researching? I think it might be a nullable boolean, since the values currently returned are either null or false. Can't be sure though.

**Comment by cohowap** [comment]
It is a bool.  Sorry, I just haven't had time to update the code.  I'll try my best to do it sometime today (US time).

**Comment by cohowap** [comment]
Let me know if what I did there is okay.  I am not a fan of exposing nullable Booleans when null carries the same impact as false.  If you want to keep it a bool? then I can change it back.

**Comment by JKorf** [comment]
I´d prefer it to be as close to the API as possible and let the implementations deal with how to handle the information. So would be nice if you could just make it a nullable bool.

**Comment by JKorf** [comment]
I had to update the package to fix some other things, so I added the Notice, LogoUrl and IsSponsored fields as well. This PR is no longer needed.

**Pull request closed without merging**
